name = "dalgardstipset"
pages_build_output_dir = "./public"
compatibility_date = "2026-08-14"

[[d1_databases]]
binding = "DB"
database_name = "dalgardstipset-db"
database_id = "683f3dbb-2533-49c6-8690-ff0dee0e56cc"